#!/usr/bin/python

import sys
import PCA_GenLib
import PCA_Gateway
			
def Run(XMLCFG,cfg_file_name):
	try:
		#print 'Start Program ...'
		try:
			TimeOut = 0.3
			PCA_GenLib.DBXMLCFGInit(XMLCFG)	
    			
			Server = PCA_Gateway.ThreadAcceptor(XMLCFG,cfg_file_name)			
			try:
				Server.dispatcher(TimeOut)
			finally:				
				Server.close()
		finally:
			PCA_GenLib.CloseLog()

	except:
 	  	print '\n\n uncaught ! < ',sys.exc_type,sys.exc_value,' >'
 	  	import traceback
		traceback.print_exc()  
		raise
   	
if __name__ == '__main__':		

  ############################### Main Program ############################################	  
  try:	
  	#print "Open cfg file"
  	try:
  		cfg_file_name = sys.argv[1]
		XMLCFG =  open(cfg_file_name,"r").read()

	except IndexError:
		raise 
	except IOError:
		XMLCFG =  open(cfg_file_name,"r").read()
	
	Run(XMLCFG,cfg_file_name)

  except:
  	print "Error or .cfg configuration file not found\n"
 	print "Msg = : <%s>,<%s>" % (sys.exc_type,sys.exc_value)
 	import traceback
	traceback.print_exc()  	
  	sys.exit()
  	
 
